services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./app:/var/www/html
            - /var/www/html/node_modules # <-- この行を追加
        command: npm run dev
